---
title: "gapminder-wrangle"
author: "zhiqiang"
date: "2020/7/9"
output: html_document
---

```{r setup,message =FALSEinclude=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
```

## Learn `dplyr` using gapminder database.
```{r}
gapminder <- read_csv("data/gapminder.csv")
view(gapminder)
show(gapminder)
str(gapminder)
```


```{r}
gapminder %>% filter(lifeExp<29)
gapminder %>% filter(country == "China")
```

```{r}

b1 <- filter(gapminder, country=="Brazil", year >=1987,year<=2007)
mean(b1$lifeExp)
```


```{r}
gap_cambodia <- filter(gapminder, country == "Cambodia") 
gap_cambodia2 <- dplyr::select(gap_cambodia, -continent, -lifeExp)
#Meet the new pipe %>% operator
gap_cambodia <- gapminder %>% filter(country == "Cambodia") %>% dplyr::select(-continent, -lifeExp)

```

```{r}

gapminder %>% 
  mutate(gdp = pop * gdpPercap)
```
```{r}
b = gapminder %>% 
  filter(continent == "Asia",year == 2007) %>% 
  mutate(pop1000 = pop/1000)
```


```{r}
c = gapminder %>% 
group_by(continent) %>% 
summarize(cont_pop = sum(pop)) %>%
ungroup()
```

```{r}
continent_year = gapminder %>% group_by(continent, year) %>% summarize(cont_pop = sum(pop))
continent_year %>% ggplot(aes(x = year, y = cont_pop, col = continent))+
  geom_line()
```

```{r}
#arrange 用来排序
gapminder %>% group_by(continent, year) %>% summarize(cont_pop = sum(pop)) %>% arrange(year)
```

```{r}
gapminder_gdp = gapminder %>% group_by(continent,year) %>% mutate(gdp = pop * gdpPercap) %>% ungroup()

gapminder_gdp %>% 
  group_by(continent) %>% 
  summarize(cont_max =max(gdp)) %>% ungroup()
```

```{r}
gapdesc <- gapminder %>% arrange(desc(country))
gapdesc %>%  filter(continnet == "Asia") %>% group_by(year) %>% summarize(maxlife = max(lifeEXP)) %>% arrange(desc(year)) %>% ungroup
```

